name: publish-backend-docker

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  publish-backend-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./backend
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/socket-app/backend:latest
            ${{ vars.DOCKER_REGISTRY }}/socket-app/backend:${{ github.sha }}
