name: publish-backend-docker

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  publish-backend-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/socket-app/backend:latest
            ${{ secrets.DOCKER_REGISTRY }}/socket-app/backend:${{ github.sha }}
          build-args: |
            NODE_ENV=production
            PORT=5000
            REDIS_URL=${{ secrets.REDIS_URL }}

      - name: Trigger deployment update
        if: ${{ secrets.DEPLOYMENT_WEBHOOK_URL != '' }}
        run: |
          RESPONSE_CODE=$(curl -X POST -w "%{http_code}" ${{ secrets.DEPLOYMENT_WEBHOOK_URL }})

          if [ "$RESPONSE_CODE" -ne 204 ]; then
            echo "Redeployment failed. Response code: $RESPONSE_CODE"
            echo "##[error]Deployment Failed! Could not automatically redeploy."
            exit 1
          else
            echo "Redeployment successful (HTTP 204)."
          fi
