name: publish-frontend-docker

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  publish-frontend-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/socket-app/frontend:latest
            ${{ vars.DOCKER_REGISTRY }}/socket-app/frontend:${{ github.sha }}
          build-args: |
            REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
            REACT_APP_SOCKET_PATH=${{ vars.REACT_APP_SOCKET_PATH }}
            NODE_ENV=production
